language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

env:
  global:
    - GLPI_STABLE="https://github.com/flyve-mdm/glpi -b 9.1.2-backport"
    - GLPI_9_1_BF="https://github.com/glpi-project/glpi -b 9.1/bugfixes"
    - GLPI_DEV="https://github.com/glpi-project/glpi -b master"
    - FLYVEMDM_STABLE="https://github.com/flyve-mdm/flyve-mdm-glpi -b master"
    - FLYVEMDM_DEV="https://github.com/btry/flyve-mdm-glpi -b feature/remove-demo"
    - FUSION_SOURCE="https://github.com/fusioninventory/fusioninventory-for-glpi -b glpi9.1+1.1"
  matrix:
    - GLPI_SOURCE=$GLPI_STABLE FLYVEMDM_SOURCE=$FLYVEMDM_DEV
    - GLPI_SOURCE=$GLPI_9_1_BF FLYVEMDM_SOURCE=$FLYVEMDM_DEV

before_script:
  - git clone --depth=50 $GLPI_SOURCE ../glpi && cd ../glpi
  - mv ../flyve-mdm-glpi-demo plugins/flyvemdmdemo
  - composer install --no-dev
  - php tools/cliinstall.php --db=glpi-test --user=travis --tests
  - cp tests/config_db.php config/config_db.php
  - mkdir plugins/fusioninventory && git clone --depth=50 $FUSION_SOURCE plugins/fusioninventory
  - mkdir plugins/flyvemdm && git clone --depth=50 $FLYVEMDM_SOURCE plugins/flyvemdm
  - cd plugins/fusioninventory
  - git apply --check  ../flyvemdm/tests/patches/fi_version-check.patch && git apply ../flyvemdm/tests/patches/fi_version-check.patch
  - cd ../..
  - cd plugins/flyvemdm && composer install --no-dev && cd ../..
  - cd plugins/flyvemdmdemo && composer install && cd ../..

script:
  - cd plugins/flyvemdmdemo
  - vendor/bin/phpunit -v
  - vendor/bin/phpcs -p --standard=vendor/glpi-project/coding-standard/GlpiStandard/ *.php front/ inc/ tests/
